# Generated by Django 3.2.7 on 2021-09-12 18:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=256)),
                ('text', models.TextField()),
                ('published_date', models.DateField(default=datetime.datetime(2021, 9, 12, 18, 28, 23, 728395, tzinfo=utc))),
            ],
        ),
    ]
